name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install PowerShell
      run: |
        sudo apt update  && sudo apt install -y curl gnupg apt-transport-https
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list'
        sudo apt update && sudo apt install -y powershell

    - name: Premake
      run: pwsh premake5.bat

    - name: Build
      run: make -C ./.build/gmake2

    # - name: Test
    #   working-directory: ${{env.SOLUTION_FILE_PATH}}/projects/bin/x64/Release
    #   run: ./ce-test.exe
